### ISSUE TITLE
运行 vite 后就卡住

### ISSUE THREAD

**Issue by imba97** [YunYouJun/tauri-vite-vue#1]
发现运行 `vite` 后就卡住了，项目目录下创建了个 `vite.config.ts.timestamp`，估计是报错了，但没报错信息

怀疑是 `Node JS` 版本的问题，我是 `v14.16.1`

![image](https://user-images.githubusercontent.com/10150208/184564936-7b075165-f2b4-48c7-9bad-cf480cdfd5d4.png)

**Comment by YunYouJun** [comment]
尝试切换了 Node.JS v14，存在一些警告信息，但跑还是能跑起来的。
建议尝试使用 bash 等类 Unix 命令行。

**Comment by YunYouJun** [comment]
Vite requires [Node.js](https://nodejs.org/en/) version **14.18+, 16+.** However, some templates require a higher Node.js version to work, please upgrade if your package manager warns about it.

> https://vitejs.dev/guide/#trying-vite-online

**Comment by imba97** [comment]
啊，原来是这样，Thank you sir
