### ISSUE TITLE
窗口崩了

### ISSUE THREAD

**Issue by mengxinssfd** [YunYouJun/tauri-vite-vue#2]
运行`tauri dev`命令后，app成功启动了窗口也能操作，但是等十几秒后就崩溃了。

报错：Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
terminating with uncaught exception of type NSException
abort() called

环境：
macOS m1，rust 1.65.0， nodes 18.6.0

**Comment by YunYouJun** [comment]
无法复现……

> macOS(intel)
> rust 1.65.0
> nodejs 16.15.0

**Comment by mengxinssfd** [comment]
好吧 只能再等等看了😂
